// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoFilterController from "./auto_filter_controller"
application.register("auto-filter", AutoFilterController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import CategorySelectorController from "./category_selector_controller"
application.register("category-selector", CategorySelectorController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ChartTabsController from "./chart_tabs_controller"
application.register("chart-tabs", ChartTabsController)

import DashboardCategoryController from "./dashboard_category_controller"
application.register("dashboard-category", DashboardCategoryController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EditModalController from "./edit_modal_controller"
application.register("edit-modal", EditModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MonthPickerController from "./month_picker_controller"
application.register("month-picker", MonthPickerController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import SlideoverCloseController from "./slideover_close_controller"
application.register("slideover-close", SlideoverCloseController)

import SlideoverController from "./slideover_controller"
application.register("slideover", SlideoverController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
