# frozen_string_literal: true

namespace :docs do
  desc "Generate all docs/generated/* artifacts"
  task generate: :environment do
    Rake::Task["docs:generate:routes"].invoke
    Rake::Task["docs:generate:schema"].invoke
  end

  namespace :generate do
    OUTPUT_DIR = Rails.root.join("docs", "generated")
    SHA = `git rev-parse --short HEAD`.strip.then { |s| s.empty? ? "unknown" : s }
    GENERATED_AT = Time.now.utc.strftime("%Y-%m-%d %H:%M UTC")

    desc "Generate docs/generated/routes.md from config/routes.rb"
    task routes: :environment do
      output = OUTPUT_DIR.join("routes.md")
      routes = `bin/rails routes`.strip
      header = <<~MD
        # Routes (generated)

        > Generated by `bin/rake docs:generate:routes` at #{GENERATED_AT} (HEAD `#{SHA}`).
        > Do not edit by hand. To update: change `config/routes.rb` and re-run the task.

      MD
      File.write(output, header + "```\n" + routes + "\n```\n")
      puts "Wrote #{output}"
    end

    desc "Generate docs/generated/schema.md summary from db/schema.rb"
    task schema: :environment do
      output = OUTPUT_DIR.join("schema.md")
      schema_path = Rails.root.join("db", "schema.rb")
      schema = File.read(schema_path)

      tables = schema.scan(/create_table\s+"([^"]+)"/).flatten.sort.uniq

      lines = [
        "# Schema summary (generated)",
        "",
        "> Generated by `bin/rake docs:generate:schema` at #{GENERATED_AT} (HEAD `#{SHA}`).",
        "> Source: `db/schema.rb`. Do not edit by hand.",
        "",
        "## Tables (#{tables.size})",
        ""
      ]
      tables.each { |table| lines << "- `#{table}`" }
      lines << ""
      lines << "## Full schema"
      lines << ""
      lines << "```ruby"
      lines << schema
      lines << "```"

      File.write(output, lines.join("\n"))
      puts "Wrote #{output}"
    end
  end
end
